.TH AR86 1 "" "Dev86" "Core Linux Distribution"

.SH NAME
ar86 - archive, modify, extract ar86(1)

.SH SYNOPSIS
.B ar86
[d|m|p|q|r|t|x [[abi [position-name] [cilouv]] archive file...

.SH DESCRIPTION
A modified GNU archiver ar86(1) that will work with dev86 architecture
targets.

.SH NOTE
This man page was written for D. E. Evans' Core Linux Distribution
[https://oberon07.com/dee/software/linux/]. Feel free to use it elsewhere.
