.TH OBJDUMP86 1 "" "Dev86" "Core Linux Distribution"

.SH NAME
objdump86 - display information from object files created with as86(1)

.SH SYNOPSIS
.B objdump86
[OBJECT-FILE]

.SH DESCRIPTION
Display information from object files created with as86(1).

.SH NOTE
This man page was written for Core Linux Distribution
[https://oberon07.com/dee/software/linux/]. Feel free to use it elsewhere.
