.TH NM86 1 "" "Bin86" "Core Linux Distribution"

.SH NAME
nm86 - list symbols from object files created with as86(1)

.SH SYNOPSIS
.B nm86
[OBJECT-FILE]

.SH DESCRIPTION
List symbols from object files created with as86(1).

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
