.TH SIZE86 1 "" "Bin86" "Core Linux Distribution"

.SH NAME
size86 - list section sizes of object files created with as86(1)

.SH SYNOPSIS
.B size86
[OBJECT-FILE]

.SH DESCRIPTION
List section sizes of object files created with as86(1).

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
