.TH ICONVCONFIG 8 "" "GNU Glibc" "Core Linux Distribution"

.SH NAME
iconvconfig - create fastloading iconv module configuration file

.SH SYNOPSIS
.B iconvconfig
[OPTION] [DIR]

.SH DESCRIPTION
Create fastloading iconv module configuration file.
.TP
.B --prefix=PATH
prefix used for all file accesses
.TP
.B -?, --help
display help information
.TP
.B --usage
display usage information
.TP
.B -V, --version
display version information

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
