.TH LOCALTIME 5 "" "Config Files" "Core Linux Distribution"

.SH NAME
localtime - symlink to timezone information

.SH DESCRIPTION
/etc/localtime is a symlink to the appropriate timezone information
located in /usr/share/zoneinfo. tzselect(1) may be used to find
the proper timezone.

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
