.TH MTRACE 1 "" "GNU Glibc" "Core Linux Distribution"

.SH NAME
mtrace - trace the memory usage of a program

.SH SYNOPSIS
.B mtrace
[OPTION] [Binary] MtraceData

.SH DESCRIPTION
Trace the memory usage of a program given a memory trace data file.
.TP
.B --help
display help information
.TP
.B --version
display version information

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
