.TH NETWORKS 5 "" "Config Files" "Core Linux Distribution"

.SH NAME
networks - network to address mappings

.SH DESCRIPTION
/etc/networks contains network to address mappings, very similar
to what is contained in /etc/hosts.  Entries are in the format:

.TP
[name] [ip address]

.TP
loopback 127.0.0.0

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
