.TH SLN 8 "" "GNU Glibc" "Core Linux Distribution"

.SH NAME
sln - statically linked ln

.SH SYNOPSIS
.B sln
[SOURCE] [DEST]

.SH DESCRIPTION
Create a symlink from DEST to SOURCE.  Sln is statically linked
for use in emergency situations.

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
