.TH SPROF 1 "" "GNU Glibc" "Core Linux Distribution"

.SH NAME
sprof - read and display shared object profiling data

.SH SYNOPSIS
.B sprof
[OPTION] SHOBJ [PROFDATA]

.SH DESCRIPTION
Read and display shared object profiling data.
.TP
.B -c, --call-pairs
print list of count paths and their number of use
.TP
.B -p, --flat-profile
generate flat profile with counts and ticks
.TP
.B -q, --graph
generate call graph
.TP
.B -?, --help
display help information
.TP
.B --usage
display usage information
.TP
.B -V, --version
display version information

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
