.TH UTMPDUMP 1 "" "Sysvinit" "Core Linux Distribution"

.SH NAME
utmpdump - dump the contents of utmp or wtmp files in a
readable format

.SH SYNOPSIS
.B utmpdump
[FILE]

.SH DESCRIPTION
Dump the contents of utmp or wtmp files in a reable format
to stdout.  FILE can be either /var/run/utmp or /var/log/wtmp.

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
