.TH GENCAT 1 "" "GNU Glibc" "Core Linux Distribution"

.SH NAME
gencat - generate message catalog

.SH SYNOPSIS
.B gencat
[OPTION] -o OUTPUT-FILE [INPUT-FILE]

.SH DESCRIPTION
Generate message catalog.
.TP
.B -H, --header=NAME
create C header file NAME containing symbol definitions
.TP
.B --new
do not use existing catalog, force new output file
.TP
.B -o, --output=NAME
write output to file NAME
.TP
.B -?, --help
display help information
.TP
.B --usage
display usage information
.TP
.B -V, --version
display version information

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
