.TH INFOKEY 1 "" "GNU Texinfo" "Core Linux Distribution"

.SH NAME
infokey - compile infokey source file to infokey file

.SH SYNOPSIS
.B infokey
[OPTION] [INPUT-FILE]

.SH DESCRIPTION
Compile infokey source file to infokey file.  Reads INPUT-FILE
(default $HOME/.infokey) and writes compiled key file to (by
default) $HOME/.info.
.TP
.B --output FILE
output to FILE instead of $HOME/.info
.TP
.B --help
display help information
.TP
.B --version
display version information

.SH NOTE
This man page was written for the Core Linux Distribution
[http://coredistro.sf.net/]. Feel free to use it elsewhere.
