FHS

MANPATH	     /usr/man

MANPATH_MAP  /sbin           /usr/man
MANPATH_MAP  /usr/bin        /usr/man

TROFF        /usr/bin/groff -Tps -mandoc
NROFF        /usr/bin/nroff -mandoc
JNROFF       /usr/bin/groff -Tnippon -mandocj
EQN          /usr/bin/eqn -Tps
NEQN         /usr/bin/eqn -Tlatin1
JNEQN        /usr/bin/eqn -Tnippon
TBL          /usr/bin/tbl
# COL        /usr/bin/col
REFER        /usr/bin/refer
PIC          /usr/bin/pic
VGRIND
GRAP
PAGER        /usr/bin/less -isR
CAT          /usr/bin/cat

CMP          /usr/bin/cmp -s

COMPRESS     /usr/bin/gzip
COMPRESS_EXT .gz

MANSECT      1:8:2:3:4:5:6:7:9

.gz          /usr/bin/gunzip -c
.bz2         /usr/bin/bzip2 -c -d
.z
.Z           /usr/bin/zcat
.F
.Y
